
// POST NEW QUESTION (PROTECTED)

POST http://localhost:5000/private/discussion/new
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzMTUwNzU5OWI0NjBlM2QwMjM0NjE0ZCIsImlhdCI6MTY2MjQ5MTk2MSwiZXhwIjoxNjYyNTc4MzYxfQ.Vhv9KulHNDRUi65_Sy_Ly8ZCiZjiPAF2zlVWBiitcbU

{
            "questionTitle":"This is a dummy question",
            "questionBody":"This is a dummy question body"
    }


###


// GET ALL QUESTIONS
GET http://localhost:5000/public/discussion/get-all-questions
Content-Type: application/json


###

 // GET SINGLE QUESTION BY QUESTION SLUG
GET http://localhost:5000/public/discussion/get-single-question/questiontitle
Content-Type: application/json




###
 // LIKE OR DISLIKE A QUESTION
PUT http://localhost:5000/private/discussion/like-dislike/questiontitle
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzMTUwNzU5OWI0NjBlM2QwMjM0NjE0ZCIsImlhdCI6MTY2MjQ5MTk2MSwiZXhwIjoxNjYyNTc4MzYxfQ.Vhv9KulHNDRUi65_Sy_Ly8ZCiZjiPAF2zlVWBiitcbU



###