// SOCIAL LOGIN
POST http://localhost:5000/public/users/auth/social 
Content-Type: application/json

{
    "idToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxODU4NWVkZGRlMDc1Mzc0ZWQzNjg0YSIsImlhdCI6MTYzNzU4ODQxNiwiZXhwIjoxNjQwMTgwNDE2fQ.2aTkJaVQl89DK6GcfsYsgsuEHQQPdJUiE1ykIOBgOqI"

}

###



// VERIFY JWT TOKEM AND CHECK SESSION EXPIRE
POST http://localhost:5000/private/users/auth/verifyToken (PROTECTED)
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxODU4NWVkZGRlMDc1Mzc0ZWQzNjg0YSIsImlhdCI6MTYzNzU4ODQxNiwiZXhwIjoxNjQwMTgwNDE2fQ.2aTkJaVQl89DK6GcfsYsgsuEHQQPdJUiE1ykIOBgOqI"

}

###